=== hinxx/hiinks/trunk/pyRamid/src/conf/iPVlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:complexType name="pv_type">
    	<xsd:sequence>
    		<xsd:element name="name" type="xsd:string"></xsd:element>
    		<xsd:element name="text" type="xsd:string"></xsd:element>
    		<xsd:element name="group" type="xsd:string"></xsd:element>
    		<xsd:element name="getSuffix" type="xsd:string"></xsd:element>
    		<xsd:element name="putSuffix" type="xsd:string"></xsd:element>
    		<xsd:element name="cmdSuffix" type="xsd:string"></xsd:element>
    		<xsd:element name="mode" type="xsd:string"></xsd:element>
    		<xsd:element name="access" type="xsd:string"></xsd:element>
    		<xsd:element name="format" type="xsd:string"></xsd:element>
    		<xsd:element name="widget" type="xsd:string"></xsd:element>
    		<xsd:element name="strings" type="xsd:string"></xsd:element>
    		<xsd:element name="enums" type="enumList_type" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    		<xsd:element name="enabled" type="xsd:boolean"></xsd:element>
    		<xsd:element name="comment" type="xsd:string"></xsd:element>
    		<xsd:element name="value" type="xsd:string"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="pvList_type">
    	<xsd:sequence>
    		<xsd:element name="pv" type="pv_type" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="enum_type">
    	<xsd:attribute name="val" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="str" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="enumList_type">
    	<xsd:sequence>
    		<xsd:element name="enum" type="enum_type"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:element name="pvList" type="pvList_type"></xsd:element>
</xsd:schema>

=== hinxx/hiinks/trunk/pyI/src/conf/iPVlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<pvList
	xsi:noNamespaceSchemaLocation="iPVlist.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema"
>

	<pv>
		<text>Dummy PV1</text>
		<name>:P:ai1</name>
		<group>dummy</group>
		<getSuffix></getSuffix>
		<putSuffix></putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLabel</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Dummy PV2</text>
		<name>:P:ai2</name>
		<group>dummy</group>
		<getSuffix></getSuffix>
		<putSuffix></putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLabel</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Dummy PV3</text>
		<name>:P:ai3</name>
		<group>dummy</group>
		<getSuffix></getSuffix>
		<putSuffix></putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLabel</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	
	<!-- Button parameters -->
	<pv>
		<text>Button X coefficient</text>
		<name>:ENV:ENV_X</name>
		<group>buttons</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Button Y coefficient</text>
		<name>:ENV:ENV_Y</name>
		<group>buttons</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Button X offset</text>
		<name>:ENV:ENV_X_OFFSET</name>
		<group>buttons</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Button Y offset</text>
		<name>:ENV:ENV_Y_OFFSET</name>
		<group>buttons</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Button Q offset</text>
		<name>:ENV:ENV_Q_OFFSET</name>
		<group>buttons</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	
	<!--  Signal & conditioning -->
	<pv>
		<text>Switches</text>
		<name>:ENV:ENV_SWITCHES</name>
		<group>signal</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>External switching</text>
		<name>:ENV:ENV_EXTSWITCH</name>
		<group>signal</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QComboBox</widget>
		<strings></strings>
		<enums>
			<enum val="0" str="Internal"></enum>
			<enum val="1" str="External"></enum>
		</enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Switching delay</text>
		<name>:ENV:ENV_SWDELAY</name>
		<group>signal</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Trigger delay</text>
		<name>:ENV:ENV_TRIGDELAY</name>
		<group>signal</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Gain</text>
		<name>:ENV:ENV_GAIN</name>
		<group>signal</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Automatic gain control (AGC)</text>
		<name>:ENV:ENV_AGC</name>
		<group>signal</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QComboBox</widget>
		<strings></strings>
		<enums>
			<enum val="0" str="Disabled"></enum>
			<enum val="1" str="Enabled"></enum>
		</enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Digital signal conditioning (DSC)</text>
		<name>:ENV:ENV_AGC</name>
		<group>signal</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QComboBox</widget>
		<strings></strings>
		<enums>
			<enum val="0" str="Disabled"></enum>
			<enum val="1" str="Unity"></enum>
			<enum val="2" str="Enabled"></enum>
			<enum val="3" str="Save factors"></enum>
		</enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>

	<!-- Interlock -->
	<pv>
		<text>Mode</text>
		<name>:ENV:ENV_ILK_MODE</name>
		<group>interlock</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QComboBox</widget>
		<strings></strings>
		<enums>
			<enum val="0" str="Disabled"></enum>
			<enum val="1" str="Enabled"></enum>
			<enum val="2" str="Gain dep"></enum>
		</enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>X low</text>
		<name>:ENV:ENV_ILK_X_LOW</name>
		<group>interlock</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>X high</text>
		<name>:ENV:ENV_ILK_X_HIGH</name>
		<group>interlock</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
		<pv>
		<text>Y low</text>
		<name>:ENV:ENV_ILK_Y_LOW</name>
		<group>interlock</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Y high</text>
		<name>:ENV:ENV_ILK_Y_HIGH</name>
		<group>interlock</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Overflow limit</text>
		<name>:ENV:ENV_ILK_OF_LIMIT</name>
		<group>interlock</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Overflow duration</text>
		<name>:ENV:ENV_ILK_OF_DUR</name>
		<group>interlock</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Gain limit</text>
		<name>:ENV:ENV_ILK_GAIN_LIMIT</name>
		<group>interlock</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix>_SP</putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-write</access>
		<format>int</format>
		<widget>QLineEdit</widget>
		<strings></strings>
		<enums></enums>
		<enabled>True</enabled>
		<comment></comment>
		<value></value>
	</pv>
	<pv>
		<text>Status</text>
		<name>:ENV:ENV_ILK_STATUS</name>
		<group>interlock</group>
		<getSuffix>_MONITOR</getSuffix>
		<putSuffix></putSuffix>
		<cmdSuffix></cmdSuffix>
		<mode>value</mode>
		<access>read-only</access>
		<format>int</format>
